# Generated by Django 4.2.dev20220728095248 on 2024-06-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashbaord', '0003_initial'),
    ]

    operations = [
        migrations.RunSQL('SELECT 1') 
    ]
