# Generated by Django 4.2.dev20220728095248 on 2024-06-06 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashbaord', '0004_auto_20240606_2044'),
    ]

    operations = [        
        migrations.RunSQL('SELECT 1')

    ]
