# Generated by Django 4.2.dev20220728095248 on 2024-06-06 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashbaord', '0005_auto_20240606_2059'),
    ]

    operations = [
        migrations.RunSQL('SELECT 1')
    ]
