# Generated by Django 4.2.dev20220728095248 on 2024-06-06 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashbaord', '0006_auto_20240606_2103'),
    ]

    operations = [
        migrations.RunSQL('SELECT 1')
    ]
